add community of support, contributing markdown file
ossrs/srs-docs pull request #10
Opened 2022-02-14 00:25 UTC by panda1986

2022-02-15 04:07 UTC, xiaosongxiaosong commented
有两种方法实现多语言的 editUrl 不一样问题，但是都有一些限制

**方法一**（建议方案）：修改 docusaurus.config.js 配置
改动方法如下：
```
          docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          // Please change this to your repo.
          editUrl: ({ versionDocsDirPath, docPath, locale, version }) => {
            return 'en-us' === locale
              ? `https://github.com/ossrs/srs-docs/edit/main/${versionDocsDirPath}/${docPath}`
              : `https://github.com/ossrs/srs-docs/edit/main/i18n/${locale}/docusaurus-plugin-content-docs/${version}/${docPath}`;
          },
          versions: {
            current: { label: '5.0.0.alpha.1' },
          },
        },
        blog: {
          showReadingTime: true,
          // Please change this to your repo.
          editUrl: ({ locale, blogDirPath, blogPath }) => {
            return 'en-us' === locale
              ? `https://github.com/ossrs/srs-docs/edit/main/${blogDirPath}/${blogPath}`
              : `https://github.com/ossrs/srs-docs/edit/main/i18n/${locale}/docusaurus-plugin-content-blog/${blogPath}`;
          },
        },
```

使用这种方法修改的问题是，所有没有配置 `custom_edit_url: null`  的文档和 Blog 在 i18n 目录中需要有拷贝，否则会出现非 `en-us` 的文档编辑链接错误

**方法二**：修改 i18n 中的文档
这个方案的问题是每个翻译文件都需要单独设置，不推荐
```
custom_edit_url: https://github.com/ossrs/srs-docs/edit/main/i18n/en-us/docusaurus-plugin-content-docs/current/community/Support.md
```

2022-02-15 04:24 UTC, xiaosongxiaosong requested changes

2022-02-15 04:24 UTC, xiaosongxiaosong commented on docusaurus.config.js
> -          editUrl: 'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
支持多语言 editUrl 区分：
https://github.com/ossrs/srs-docs/pull/10#issuecomment-1039835713

2022-02-15 04:24 UTC, xiaosongxiaosong commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/community/Contributing.md
> +1. 请先从尝试fix bug开始 [Issues: good first issue](https://github.com/ossrs/srs/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).
中文文档的中数字和英文前后建议加上空格
“请先从尝试fix bug开始“ 改成 ”请先从尝试 fix bug 开始“

2022-02-15 04:24 UTC, xiaosongxiaosong commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/community/Contributing.md
> +3. 我们将会尽快review你的PR.
`review` 前后和 `PR` 的前面加上空格

2022-02-15 04:24 UTC, xiaosongxiaosong commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/community/Support.md
> +
”以及SRS的未来“ SRS 前后空格

2022-02-15 04:24 UTC, xiaosongxiaosong commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/community/Support.md
> +* B站专栏
”B站“ 改成 ”B 站“

2022-02-15 04:24 UTC, xiaosongxiaosong commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/community/Support.md
> +
SRS 需要大写且前后加空格
”在这里你将看到srs各种使用场景的精彩视频“ 改成  ”在这里你将看到 SRS 各种使用场景的精彩视频“

2022-02-15 04:24 UTC, xiaosongxiaosong commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/community/Support.md
> +对于新功能，请先阅读[Never file an issue unless read it](https://github.com/ossrs/srs/issues/2716)，提问前请先阅读文档：
”Never file an issue unless read it“ 改成”提 Issue 前必读“
同时这句话不太通顺，好像表达了两个意思，又有些重复，建议分成两段，一段说新功能，一段说提 Issue

2022-02-15 04:24 UTC, xiaosongxiaosong commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/community/Support.md
> +SRS的最新消息，请关注srs的公众号。
第一个SRS 后需要加空格，第二个 SRS 需要大写且前后加空格

2022-02-15 04:24 UTC, xiaosongxiaosong commented on docs/community/Support.md
> +For new feature requests, you should first read[Never file an issue unless read it](https://github.com/ossrs/srs/issues/2716)，before fire an issue, please read：
这句话不太通顺，好像表达了两个意思，又有些重复，建议分成两段，一段说新功能，一段说提 Issue

2022-02-15 09:33 UTC, panda1986 commented
> 有两种方法实现多语言的 editUrl 不一样问题，但是都有一些限制
> 
> **方法一**（建议方案）：修改 docusaurus.config.js 配置 改动方法如下：
> 
> ```
>           docs: {
>           sidebarPath: require.resolve('./sidebars.js'),
>           // Please change this to your repo.
>           editUrl: ({ versionDocsDirPath, docPath, locale, version }) => {
>             return 'en-us' === locale
>               ? `https://github.com/ossrs/srs-docs/edit/main/${versionDocsDirPath}/${docPath}`
>               : `https://github.com/ossrs/srs-docs/edit/main/i18n/${locale}/docusaurus-plugin-content-docs/${version}/${docPath}`;
>           },
>           versions: {
>             current: { label: '5.0.0.alpha.1' },
>           },
>         },
>         blog: {
>           showReadingTime: true,
>           // Please change this to your repo.
>           editUrl: ({ locale, blogDirPath, blogPath }) => {
>             return 'en-us' === locale
>               ? `https://github.com/ossrs/srs-docs/edit/main/${blogDirPath}/${blogPath}`
>               : `https://github.com/ossrs/srs-docs/edit/main/i18n/${locale}/docusaurus-plugin-content-blog/${blogPath}`;
>           },
>         },
> ```
> 
> 使用这种方法修改的问题是，所有没有配置 `custom_edit_url: null` 的文档和 Blog 在 i18n 目录中需要有拷贝，否则会出现非 `en-us` 的文档编辑链接错误
> 
> **方法二**：修改 i18n 中的文档 这个方案的问题是每个翻译文件都需要单独设置，不推荐
> 
> ```
> custom_edit_url: https://github.com/ossrs/srs-docs/edit/main/i18n/en-us/docusaurus-plugin-content-docs/current/community/Support.md
> ```

方案一吧，我最先想的也是这个；方案二不考虑了

2022-02-15 12:20 UTC, panda1986 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/community/Support.md
> +对于新功能，请先阅读[Never file an issue unless read it](https://github.com/ossrs/srs/issues/2716)，提问前请先阅读文档：
还是只用issue requests吧，github里feature只有tag

2022-02-16 01:44 UTC, xiaosongxiaosong requested changes

2022-02-16 01:44 UTC, xiaosongxiaosong commented on docusaurus.config.js
> +          editUrl: ({ locale, blogDirPath, blogPath, permalink }) =>
blog 的 editUrl 需要改下
```js
          editUrl: ({ locale, blogDirPath, blogPath }) => {
            return 'en-us' === locale
              ? `https://github.com/ossrs/srs-docs/edit/main/${blogDirPath}/${blogPath}`
              : `https://github.com/ossrs/srs-docs/edit/main/i18n/${locale}/docusaurus-plugin-content-blog/${blogPath}`;
          },
```

2022-02-16 10:05 UTC, merged