update CPU adaptation backup mentor info
ossrs/srs-docs pull request #13
Opened 2022-02-18 09:01 UTC by gh-Devin

2022-02-19 07:19 UTC, xiaosongxiaosong requested changes

2022-02-19 07:19 UTC, xiaosongxiaosong commented on blog/2022-02-10-GSoC.md
> -|Backup Mentor|Zhihong Xiao(hondaxiao@tencent.com)|
目前的写法新增的备份导师不会显示在界面上
```
|Backup Mentor|Zhihong Xiao(hondaxiao@tencent.com)|Feng Yi yifeng1983@gmail.com|
```
需要修改成
```
|Backup Mentor|Zhihong Xiao(hondaxiao@tencent.com), Feng Yi yifeng1983@gmail.com|
```

![image](https://user-images.githubusercontent.com/2703455/154791019-4a736483-6b1b-4d81-8425-95ed71bdd067.png)

2022-02-19 08:00 UTC, xiaosongxiaosong requested changes

2022-02-21 01:56 UTC, gh-Devin commented on blog/2022-02-10-GSoC.md
> +|Backup Mentor|Zhihong Xiao(hondaxiao@tencent.com)|Feng Yi yifeng1983@gmail.com|
done

2022-02-21 02:04 UTC, xiaosongxiaosong approved these changes

2022-02-21 09:43 UTC, merged